### ISSUE TITLE
"error: package directory 'aiohttp==3\8\3' does not exist" when trying to install

### ISSUE THREAD

**Issue by Probably-Idiot** [CuzImSyntax/TrivIO#1]
When I try to install trivio from the instructions on readme.md I get this issue. Here's the output:
running install
running bdist_egg
running egg_info
writing TrivIO.egg-info\PKG-INFO
writing dependency_links to TrivIO.egg-info\dependency_links.txt
writing top-level names to TrivIO.egg-info\top_level.txt
error: package directory 'aiohttp==3\8\3' does not exist

**Comment by CuzImSyntax** [comment]
Which Python version are you using? I just checked it myself and I had no problems installing it. 
Nevertheless I think some of the requirements are useless as they are installed by default. I will try to update the requirements as soon as possible.

**Comment by Probably-Idiot** [comment]
I think I’m using 3.10, but I’ll be able to check tomorrow.

**Comment by CuzImSyntax** [comment]
@Probably-Idiot I found a problem in the setup.py file, I will fix it in a few hours, when im home.

**Comment by CuzImSyntax** [comment]
@Probably-Idiot I just pushed some changes. Everything should work as expected now.

**Comment by Probably-Idiot** [comment]
@CuzImSyntax Works great now, thanks!
